[project]
name = "ntprop"
version = "0.1.4"
description = "A way to create transparent NetworkTables variables"
authors = [
    {name = "Kellen Watt",email = "kellen@wattsoft.dev"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyntcore (>=2026.2.2,<2027.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
